@startuml WebRTC_Android_Api_Class

/'PeerConnection所有资源创建工厂'/
class PeerConnectionFactory {

}

MediaStream <.. PeerConnectionFactory

/'媒体限制条件，创建媒体源时使用'/
class MediaConstraints {

}
class MediaStream {

}
AudioTrack <-- MediaStream
MediaStreamTrack <|-- AudioTrack

VideoTrack <-- MediaStream
MediaStreamTrack <|-- VideoTrack
VideoSource <-- VideoTrack
class VideoSource {

}
MediaSource <|-- VideoSource
class MediaSource {
    
}
VideoCapturer <-- VideoSource
MediaConstraints <-- VideoSource

class MediaStreamTrack {

}

JavaAudioDeviceModule <-- PeerConnectionFactory
/'音频设备模块'/
class JavaAudioDeviceModule {

}
AudioDeviceModule <|.. JavaAudioDeviceModule
interface AudioDeviceModule {
    void release()
    void setSpeakerMute(boolean mute)
    void setMicrophoneMute(boolean mute)
}
AudioManager <-- JavaAudioDeviceModule
/'音量和响铃模式的控制'/
class AudioManager {

}
WebRtcAudioRecord <-- JavaAudioDeviceModule
/'音频录制（输入）'/
class WebRtcAudioRecord {

}
/'音频播放（输出）'/
WebRtcAudioTrack <-- JavaAudioDeviceModule
AudioEncoderFactoryFactory <-- PeerConnectionFactory
/'音频编码器'/
interface AudioEncoderFactoryFactory {

}
AudioEncoderFactoryFactory <|.. BuiltinAudioEncoderFactoryFactory
AudioDecoderFactoryFactory <-- PeerConnectionFactory
/'音频解码器'/
interface AudioDecoderFactoryFactory {

}
AudioDecoderFactoryFactory <|.. BuiltinAudioDecoderFactoryFactory

@enduml